<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_l_jhkHhMEeuzuKS1expDjA" name="ConnectorBdmGenerationDemo" author="laurent" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_l_jhkXhMEeuzuKS1expDjA" documentation="Demo process with BDM generation connector" name="connectorBdmGenerationDemo">
      <elements xmi:type="process:Lane" xmi:id="_l_jhknhMEeuzuKS1expDjA" name="Employee lane" actor="_l_jhq3hMEeuzuKS1expDjA">
        <elements xmi:type="process:StartEvent" xmi:id="_l_jhk3hMEeuzuKS1expDjA" name="Start1" outgoing="_l_jhqHhMEeuzuKS1expDjA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l_jhlHhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l_jhlXhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l_jhlnhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_r23TMHhMEeuzuKS1expDjA" documentation="Reads database and generate BDM zip file as a process document&#xA;" name="call connector" outgoing="_tyNlkHhMEeuzuKS1expDjA" incoming="_l_jhqHhMEeuzuKS1expDjA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l_jhmHhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l_jhmXhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l_jhmnhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_64bboHhREeuzuKS1expDjA" name="bdm" definitionId="bdm-generation" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_64bboXhREeuzuKS1expDjA" definitionId="bdm-generation" version="1.0.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_64bbonhREeuzuKS1expDjA" key="jdbcUrl">
                <expression xmi:type="expression:Expression" xmi:id="_64bbo3hREeuzuKS1expDjA" name="jdbcUrl" content="jdbcUrl" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_EoyM8Hp3Eeur-7_XXlfihg" name="jdbcUrl" typeClassname="java.lang.String" description="jdbc:postgresql://localhost:5435/dvdrental"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_64bbpHhREeuzuKS1expDjA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_64bbpXhREeuzuKS1expDjA" name="jdbcUsername" content="jdbcUsername" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_EoyM8Xp3Eeur-7_XXlfihg" name="jdbcUsername" typeClassname="java.lang.String" description="postgres"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_64bbpnhREeuzuKS1expDjA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_64bbp3hREeuzuKS1expDjA" name="jdbcPassword" content="jdbcPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Eoy0AHp3Eeur-7_XXlfihg" name="jdbcPassword" typeClassname="java.lang.String" description="example"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_64bbqHhREeuzuKS1expDjA" key="driver">
                <expression xmi:type="expression:Expression" xmi:id="_64bbqXhREeuzuKS1expDjA" name="jdbcDriver" content="jdbcDriver" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Eoy0AXp3Eeur-7_XXlfihg" name="jdbcDriver" typeClassname="java.lang.String" description="org.postgresql.Driver"/>
                </expression>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_64bbqnhREeuzuKS1expDjA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_64bbq3hREeuzuKS1expDjA" name="metaData" content="metaData" type="TYPE_VARIABLE" returnType="java.lang.Object">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_64bbrHhREeuzuKS1expDjA" name="metaData" dataType="_l_jhwnhMEeuzuKS1expDjA" className="java.lang.Object"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_64bbrXhREeuzuKS1expDjA" name="sqlMetadata" content="sqlMetadata" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_64bbrnhREeuzuKS1expDjA" name="sqlMetadata" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_64bbr3hREeuzuKS1expDjA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_64bbsHhREeuzuKS1expDjA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_64bbsXhREeuzuKS1expDjA" name="bdmZip" content="bdmZip" type="DOCUMENT_REF_TYPE">
                <referencedElements xmi:type="process:Document" xmi:id="_64bbsnhREeuzuKS1expDjA" name="bdmZip"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_64bbs3hREeuzuKS1expDjA" name="bdmZipFile" content="bdmZipFile" type="CONNECTOR_OUTPUT_TYPE" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                <referencedElements xmi:type="definition:Output" xmi:id="_64bbtHhREeuzuKS1expDjA" name="bdmZipFile" type="org.bonitasoft.engine.bpm.document.DocumentValue"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_64bbtXhREeuzuKS1expDjA" type="DOCUMENT_CREATE_UPDATE"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_l_jhm3hMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_l_jhnHhMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_l_jhnXhMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_l_jhnnhMEeuzuKS1expDjA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_l_jhn3hMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_siS10HhMEeuzuKS1expDjA" name="End1" incoming="_vuK78HhMEeuzuKS1expDjA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_siTc4XhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_siTc4HhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_siTc4nhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_uRGhAHhMEeuzuKS1expDjA" documentation="Go to case overview to download zip file, them import it into Bonita studio&#xA;" name="review" outgoing="_vuK78HhMEeuzuKS1expDjA" incoming="_tyNlkHhMEeuzuKS1expDjA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tyJUInhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tyJUIXhMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tyJUI3hMEeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tyJUJHhMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tyJUJXhMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tyJUJnhMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tyJUKHhMEeuzuKS1expDjA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tyJUJ3hMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uRGhCnhMEeuzuKS1expDjA" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_b46IMHuuEeu8P_RUzCg8Eg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uRGhCXhMEeuzuKS1expDjA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uRGhDHhMEeuzuKS1expDjA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:JavaObjectData" xmi:id="_slIVIHhREeuzuKS1expDjA" name="metaData" dataType="_l_jhwnhMEeuzuKS1expDjA" className="java.lang.Object">
        <defaultValue xmi:type="expression:Expression" xmi:id="_slIVIXhREeuzuKS1expDjA" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_l_jhpHhMEeuzuKS1expDjA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_xEf8EXhUEeuzuKS1expDjA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_l_jhpnhMEeuzuKS1expDjA">
        <targetForm xmi:type="expression:Expression" xmi:id="_l_jhp3hMEeuzuKS1expDjA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l_jhqHhMEeuzuKS1expDjA" target="_r23TMHhMEeuzuKS1expDjA" source="_l_jhk3hMEeuzuKS1expDjA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l_jhqXhMEeuzuKS1expDjA"/>
        <condition xmi:type="expression:Expression" xmi:id="_l_jhqnhMEeuzuKS1expDjA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tyNlkHhMEeuzuKS1expDjA" target="_uRGhAHhMEeuzuKS1expDjA" source="_r23TMHhMEeuzuKS1expDjA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tyNlkXhMEeuzuKS1expDjA"/>
        <condition xmi:type="expression:Expression" xmi:id="_tyNlknhMEeuzuKS1expDjA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vuK78HhMEeuzuKS1expDjA" target="_siS10HhMEeuzuKS1expDjA" source="_uRGhAHhMEeuzuKS1expDjA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vuK78XhMEeuzuKS1expDjA"/>
        <condition xmi:type="expression:Expression" xmi:id="_vuK78nhMEeuzuKS1expDjA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_l_jhq3hMEeuzuKS1expDjA" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_9bBUMHhREeuzuKS1expDjA" name="Qualification" version="7.12.0-004" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_9bBUP3hREeuzuKS1expDjA">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_9bBUQHhREeuzuKS1expDjA" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_9bBUQXhREeuzuKS1expDjA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_9bBUQnhREeuzuKS1expDjA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_9bBUQ3hREeuzuKS1expDjA">
              <role>member</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_9bBURHhREeuzuKS1expDjA"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_9bBUMXhREeuzuKS1expDjA" type="CONNECTOR" definitionId="bdm-generation" definitionVersion="1.0.0" implementationId="bdm-generation-impl" implementationVersion="1.3"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_9bBUMnhREeuzuKS1expDjA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_9bBUM3hREeuzuKS1expDjA" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_W7hBIHuuEeu8P_RUzCg8Eg" id="bdm-generation-impl-1.3">
            <fragments xmi:type="configuration:Fragment" xmi:id="_W7nHwHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="connector-bdm-generation-1.3.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W7o88HuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="jsr305-3.0.2.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W7rZMHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="failureaccess-1.0.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W7t1cHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W7yG4HuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="error_prone_annotations-2.3.4.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W71KMHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="HikariCP-3.4.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W-UdgHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="postgresql-42.2.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W-YH4HuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="guava-30.1-jre.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_W-n_gHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="checker-qual-3.5.0.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_XBBzQHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="j2objc-annotations-1.3.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_XBGEsHuuEeu8P_RUzCg8Eg" key="bdm-generation-impl -- 1.3" value="bdm-generation-impl-1.3.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_9bBUO3hREeuzuKS1expDjA" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_9bBUPHhREeuzuKS1expDjA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_9bBUPXhREeuzuKS1expDjA" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_9bBUPnhREeuzuKS1expDjA" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_E7MyoHp3Eeur-7_XXlfihg" name="jdbcUrl" value="jdbc:postgresql://localhost:5435/dvdrental&#xA;&#xA;" typeClassname="java.lang.String" description="jdbc:postgresql://localhost:5435/dvdrental"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_E7MyoXp3Eeur-7_XXlfihg" name="jdbcUsername" value="postgres" typeClassname="java.lang.String" description="postgres"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_E7Myonp3Eeur-7_XXlfihg" name="jdbcPassword" value="example" typeClassname="java.lang.String" description="example"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_E7Myo3p3Eeur-7_XXlfihg" name="jdbcDriver" value="org.postgresql.Driver" typeClassname="java.lang.String" description="org.postgresql.Driver"/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_7zEwgHp2Eeur-7_XXlfihg" name="jdbcUrl" typeClassname="java.lang.String" description="jdbc:postgresql://localhost:5435/dvdrental"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_-lIocHp2Eeur-7_XXlfihg" name="jdbcUsername" typeClassname="java.lang.String" description="postgres"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Bo6igHp3Eeur-7_XXlfihg" name="jdbcPassword" typeClassname="java.lang.String" description="example"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_EPgKQHp3Eeur-7_XXlfihg" name="jdbcDriver" typeClassname="java.lang.String" description="org.postgresql.Driver"/>
      <contract xmi:type="process:Contract" xmi:id="_l_jhrHhMEeuzuKS1expDjA"/>
      <documents xmi:type="process:Document" xmi:id="_vGYw8HhREeuzuKS1expDjA" name="bdmZip">
        <mimeType xmi:type="expression:Expression" xmi:id="_vGYw8XhREeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_vGYw8nhREeuzuKS1expDjA" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_vGYw83hREeuzuKS1expDjA" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_l_jhrXhMEeuzuKS1expDjA">
        <name xmi:type="expression:Expression" xmi:id="_l_jhrnhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_l_jhr3hMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_l_jhsHhMEeuzuKS1expDjA">
        <name xmi:type="expression:Expression" xmi:id="_l_jhsXhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_l_jhsnhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_l_jhs3hMEeuzuKS1expDjA">
        <name xmi:type="expression:Expression" xmi:id="_l_jhtHhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_l_jhtXhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_l_jhtnhMEeuzuKS1expDjA">
        <name xmi:type="expression:Expression" xmi:id="_l_jht3hMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_l_jhuHhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_l_jhuXhMEeuzuKS1expDjA">
        <name xmi:type="expression:Expression" xmi:id="_l_jhunhMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_l_jhu3hMEeuzuKS1expDjA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_l_jhvHhMEeuzuKS1expDjA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_l_jhvXhMEeuzuKS1expDjA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_l_jhvnhMEeuzuKS1expDjA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_l_jhv3hMEeuzuKS1expDjA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_l_jhwHhMEeuzuKS1expDjA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_l_jhwXhMEeuzuKS1expDjA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_l_jhwnhMEeuzuKS1expDjA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_l_jhw3hMEeuzuKS1expDjA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_l_jhxHhMEeuzuKS1expDjA" name="Business_Object"/>
    <datatypes xmi:type="process:EnumType" xmi:id="_4S48wHhREeuzuKS1expDjA" name="OptionList1"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_l_jhxXhMEeuzuKS1expDjA" type="Process" element="_l_jhkHhMEeuzuKS1expDjA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_l_jhxnhMEeuzuKS1expDjA" type="2007" element="_l_jhkXhMEeuzuKS1expDjA">
      <children xmi:type="notation:DecorationNode" xmi:id="_l_jhx3hMEeuzuKS1expDjA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_l_jhyHhMEeuzuKS1expDjA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_l_jhyXhMEeuzuKS1expDjA" type="3007" element="_l_jhknhMEeuzuKS1expDjA">
          <children xmi:type="notation:DecorationNode" xmi:id="_l_jhynhMEeuzuKS1expDjA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_l_jhy3hMEeuzuKS1expDjA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_l_jhz3hMEeuzuKS1expDjA" type="3002" element="_l_jhk3hMEeuzuKS1expDjA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_l_jh0HhMEeuzuKS1expDjA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_l_jh0XhMEeuzuKS1expDjA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l_jh0nhMEeuzuKS1expDjA" x="60" y="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r25vcHhMEeuzuKS1expDjA" type="3027" element="_r23TMHhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r26WgHhMEeuzuKS1expDjA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r25vcXhMEeuzuKS1expDjA" x="160" y="60" width="149" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_siUD8HhMEeuzuKS1expDjA" type="3003" element="_siS10HhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_siUD8nhMEeuzuKS1expDjA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_siUD83hMEeuzuKS1expDjA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_siUD8XhMEeuzuKS1expDjA" x="637" y="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uRHIEHhMEeuzuKS1expDjA" type="3005" element="_uRGhAHhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uRHIEnhMEeuzuKS1expDjA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uRHIEXhMEeuzuKS1expDjA" x="371" y="60" width="141" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_l_jh03hMEeuzuKS1expDjA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_l_jh1HhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_l_jh1XhMEeuzuKS1expDjA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_l_jh1nhMEeuzuKS1expDjA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l_jh13hMEeuzuKS1expDjA"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_l_jh2HhMEeuzuKS1expDjA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_l_jh2XhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_l_jh2nhMEeuzuKS1expDjA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_l_jh23hMEeuzuKS1expDjA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l_jh3HhMEeuzuKS1expDjA" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_l_jh3XhMEeuzuKS1expDjA"/>
    <edges xmi:type="notation:Connector" xmi:id="_l_jh3nhMEeuzuKS1expDjA" type="4001" element="_l_jhqHhMEeuzuKS1expDjA" source="_l_jhz3hMEeuzuKS1expDjA" target="_r25vcHhMEeuzuKS1expDjA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l_jh33hMEeuzuKS1expDjA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l_jh4HhMEeuzuKS1expDjA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l_jh4XhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l_jh4nhMEeuzuKS1expDjA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tyOMoHhMEeuzuKS1expDjA" type="4001" element="_tyNlkHhMEeuzuKS1expDjA" source="_r25vcHhMEeuzuKS1expDjA" target="_uRHIEHhMEeuzuKS1expDjA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tyOMo3hMEeuzuKS1expDjA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tyOMpHhMEeuzuKS1expDjA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tyOMoXhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tyOMonhMEeuzuKS1expDjA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vuLjAHhMEeuzuKS1expDjA" type="4001" element="_vuK78HhMEeuzuKS1expDjA" source="_uRHIEHhMEeuzuKS1expDjA" target="_siUD8HhMEeuzuKS1expDjA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vuLjA3hMEeuzuKS1expDjA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vuLjBHhMEeuzuKS1expDjA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vuLjAXhMEeuzuKS1expDjA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vuLjAnhMEeuzuKS1expDjA" points="[0, 0, -182, 41]$[179, -27, -3, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vuMxIHhMEeuzuKS1expDjA" id="(1.0,0.52)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
